name: pytest

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "main"

jobs:
  build-pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  update-readme:
    needs: build-pytest
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-leetcode
      - name: Auto update README
        run: |
          python -m util.update_readme
      - name: Check for changes
        id: git_status
        run: |
          git add README.md
          git diff-index --quiet HEAD || echo "changes"
      - name: Commit and push changes
        if: steps.git_status.outputs.changes == 'changes'
        run: |
          git config --global user.name 'github nickname'
          git config --global user.email 'github email'
          git add "README.md"
          git commit -am "auto: updating README.md"
          git push
