name: update readme

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-leetcode
      - name: Auto update README
        run: |
          python -m util.update_readme
      - name: Commit changes
        run: |
          git config --global user.name 'github nickname'
          git config --global user.email 'github email'
          git add "README.md"
          git commit -am "auto: updating README.md"
      - name: Push changes
        run: |
          git push
